version: "3.3"
services:
  api-preview:
    build:
      context: .
      dockerfile: api-preview.Dockerfile
    entrypoint: '/watch.sh'
    command: '/api/api.yaml'
    ports:
      - "80:8000"
    volumes:
      - ./swagger:/api
